# Pull the base image with python 3.7 as a runtime for your Lambda
FROM public.ecr.aws/lambda/python:3.7

# Copy the model used for inference 
RUN mkdir models
COPY model/*.tflight ./models/

# Copy the earlier created app.py 
COPY app.py ./

# Copy the earlier created requirements.txt 
COPY requirements.txt ./

# Install the python requirements from requirements.txt
RUN python3.7 -m pip install -r requirements.txt

# Set the CMD to your handler
CMD ["app.lambda_handler"]